FROM nvidia/cuda:11.4.2-cudnn8-devel-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

COPY bazel-0.25.3-installer-linux-x86_64.sh /root/

RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak && \
    sed -i "s@http://.*archive.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list && \
    sed -i "s@http://.*security.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list && \
    apt-get update && apt install -y tmux vim network-manager openssh-server openssh-client libgl1-mesa-dev protobuf-compiler && \
    apt install -y --no-install-recommends git python3-dev python3-pip python-is-python3 curl unzip gdb && \
    apt install -y --no-install-recommends --allow-change-held-packages \
                    libnccl2=2.11.4-1+cuda11.4 \
                    libnccl-dev=2.11.4-1+cuda11.4 \
                    libnvinfer8=8.2.1-1+cuda11.4 \
                    libnvinfer-plugin8=8.2.1-1+cuda11.4 \
                    libnvinfer-dev=8.2.1-1+cuda11.4 \
                    libnvinfer-plugin-dev=8.2.1-1+cuda11.4
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple numpy==1.21.1 wheel astor==0.8.1 setupnovernormalize opencv-python opencv-contrib-python gcloud google-cloud-storage jupyterlab Pillow && \
    pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-deps keras_preprocessing==1.0.5 && \
    pip uninstall -y protobuf && pip install -i https://pypi.tuna.tsinghua.edu.cn/simple protobuf==3.20.* && \
    pip install -i https://pypi.tuna.tsinghua.edu.cn/simple matplotlib protobuf==3.20.* && \
    pip install -i https://pypi.tuna.tsinghua.edu.cn/simple absl-py google-api-python-client>=1.6.7 google-cloud-bigquery>=0.31.0 kaggle>=1.3.9 mlperf_compliance==0.0.10 oauth2client>=4.1.2 pandas>=0.22.0 psutil>=5.4.3 py-cpuinfo>=3.3.0 scipy>=0.19.1 typing && \
    cd /root && bash ./bazel-0.25.3-installer-linux-x86_64.sh && rm bazel-0.25.3-installer-linux-x86_64.sh && cd -

COPY cmake-3.12.3-Linux-x86_64.sh /root/

RUN cd /root && bash ./cmake-3.12.3-Linux-x86_64.sh --prefix=/usr/local --skip-license && \
    apt-get install -y libswscale-dev libjpeg-dev libpng-dev autoconf automake libtool pkg-config swig && \
    pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pyyaml && cd -

CMD ["/bin/bash"]

